# Generated by Django 5.0.7 on 2024-07-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('subject_specialization', models.CharField(max_length=20)),
                ('years_of_experience', models.IntegerField()),
                ('office_hours', models.CharField(max_length=20)),
                ('biography', models.TextField()),
                ('course_taught', models.CharField(max_length=50)),
                ('hire_date', models.DateField()),
                ('department', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
                ('address', models.CharField(max_length=30)),
                ('profile_picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
