# Generated by Django 5.0.7 on 2024-07-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_id', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('enrolment_capacity', models.PositiveSmallIntegerField()),
                ('department_id', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
                ('Syllabus', models.TextField()),
                ('course_duration', models.IntegerField()),
            ],
        ),
    ]
